config/routes.rb
Rails.application.routes.draw do
  resources :administradores
  resources :pedidos do
    resources :pedido_produtos
  end
  resources :clientes
  resources :produtos 
  resources :tipo_produtos

  #admin
  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/sair', to: 'login#sair'

  #autenticacao
  get '/login', to: 'login#index'
  post '/login/autenticar', to: 'login#autenticar'
  get '/login/sair', to: 'login#sair'
  
  # ecommerce
  get '/produto/:produto_id', to: 'ecommerce#index'
  get '/produto/:produto_id/adicionar', to: 'ecommerce#adicionar'
  get '/produto/:produto_id/remover', to: 'ecommerce#remover'
  get '/carrinho', to: 'ecommerce#carrinho'
  get '/carrinho/fechar', to: 'ecommerce#fechar_carrinho'
  get '/cliente/logar', to: 'ecommerce#login'
  post '/cliente/login', to: 'ecommerce#fazer_login_cliente'
  get '/cliente/cadastrar', to: 'ecommerce#cadastrar'
  post '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  patch '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  get '/cliente/sair', to: 'ecommerce#sair'
  get '/cliente/compra-concluida', to: 'ecommerce#compra_concluida'
  post '/cliente/concluir-pagamento', to: 'ecommerce#concluir_pagamento'
  get '/cliente/pagamento', to: 'ecommerce#confirmar_pagamento'

  
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pedido_produto.rb
class PedidoProduto < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
end

app/controllers/pedido_produtos_controller.rb
class PedidoProdutosController < ApplicationController
  before_action :set_pedido_produto, only: %i[ show edit update destroy ]
  before_action :set_pedido
  # GET /pedido_produtos or /pedido_produtos.json
  def index
    @pedido_produtos = PedidoProduto.where(pedido_id: @pedido.id)
  end

  # GET /pedido_produtos/1 or /pedido_produtos/1.json
  def show
  end

  # GET /pedido_produtos/new
  def new
    @pedido_produto = PedidoProduto.new
  end

  # GET /pedido_produtos/1/edit
  def edit
  end

  # POST /pedido_produtos or /pedido_produtos.json
  def create
    @pedido_produto = PedidoProduto.new(pedido_produto_params)
    @pedido_produto.pedido = @pedido

    respond_to do |format|
      if @pedido_produto.save
        format.html { redirect_to pedido_pedido_produtos_path(@pedido), notice: "Pedido produto was successfully created." }
        format.json { render :show, status: :created, location: @pedido_produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedido_produtos/1 or /pedido_produtos/1.json
  def update
    respond_to do |format|
      if @pedido_produto.update(pedido_produto_params)
        format.html { redirect_to  pedido_pedido_produtos_path(@pedido), notice: "Pedido produto was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido_produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedido_produtos/1 or /pedido_produtos/1.json
  def destroy
    @pedido_produto.destroy
    respond_to do |format|
      format.html { redirect_to  pedido_pedido_produtos_path(@pedido), notice: "Pedido produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido= Pedido.find(params[:pedido_id])
    end

    def set_pedido_produto
      @pedido_produto = PedidoProduto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_produto_params
      params.require(:pedido_produto).permit(:pedido_id, :produto_id, :valor, :quantidade)
    end
end

app/helpers/pedido_produtos_helper.rb
module PedidoProdutosHelper
end

app/views/pedido_produtos/_form.html.erb
<%= form_for([@pedido, @pedido_produto], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @pedido_produto.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@pedido_produto.errors.count, "error") %> prohibited this pedido_produto from being saved:</h4>

      <ul>
      <% @pedido_produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :produto_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :produto_id, Produto.all.collect{|p| [p.nome, p.id]}, {}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :valor, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantidade, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/pedido_produtos/edit.html.erb
<div class="page-header">
  <%= link_to pedido_pedido_produtos_path(@pedido), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Votar
  <% end %>
  <%= link_to pedido_pedido_produtos_path(@pedido, @pedido_produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostar
  <% end %>
  <h1>Editando item pedido</h1>
</div>

<%= render 'form' %>

app/views/pedido_produtos/index.html.erb
<div class="page-header">
  <%= link_to new_pedido_pedido_produto_path(@pedido), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Pedido produto
  <% end %>
  <h1>Listando itens pedidos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Pedido</th>
            <th>Produto</th>
            <th>Valor</th>
            <th>Quantidade</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @pedido_produtos) do |pedido_produto| %>
            <td><%= pedido_produto.pedido.id %></td>
            <td><%= pedido_produto.produto.nome %></td>
            <td><%= pedido_produto.valor %></td>
            <td><%= pedido_produto.quantidade %></td>
            <td><%= link_to 'Mostrar', pedido_pedido_produto_path(@pedido, pedido_produto) %></td>
        <td><%= link_to 'Editar', edit_pedido_pedido_produto_path(@pedido, pedido_produto) %></td>
        <td><%= link_to 'Deletar', pedido_pedido_produto_path(@pedido, pedido_produto), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pedido_produtos/new.html.erb
<div class="page-header">
  <%= link_to pedido_pedido_produtos_path(@pedido), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo itens pedido </h1>
</div>

<%= render 'form' %>

app/views/pedido_produtos/show.html.erb
<div class="page-header">
  <%= link_to pedido_pedido_produtos_path(@pedido), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_pedido_pedido_produto_path(@pedido, @pedido_produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar item pedido</h1>
</div>

<dl class="dl-horizontal">
  <dt>Pedido:</dt>
  <dd><%= @pedido_produto.pedido.id %></dd>

  <dt>Produto:</dt>
  <dd><%= @pedido_produto.produto.nome %></dd>

  <dt>Valor:</dt>
  <dd><%= @pedido_produto.valor %></dd>

  <dt>Quantidade:</dt>
  <dd><%= @pedido_produto.quantidade %></dd>

</dl>