config/routes.rb
Rails.application.routes.draw do
  resources :administradores
  resources :pedidos do
    resources :pedido_produtos
  end
  resources :clientes
  resources :produtos 
  resources :tipo_produtos

  #admin
  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/sair', to: 'login#sair'

  #autenticacao
  get '/login', to: 'login#index'
  post '/login/autenticar', to: 'login#autenticar'
  get '/login/sair', to: 'login#sair'
  
  # ecommerce
  get '/produto/:produto_id', to: 'ecommerce#index'
  get '/produto/:produto_id/adicionar', to: 'ecommerce#adicionar'
  get '/produto/:produto_id/remover', to: 'ecommerce#remover'
  get '/carrinho', to: 'ecommerce#carrinho'
  get '/carrinho/fechar', to: 'ecommerce#fechar_carrinho'
  get '/cliente/logar', to: 'ecommerce#login'
  post '/cliente/login', to: 'ecommerce#fazer_login_cliente'
  get '/cliente/cadastrar', to: 'ecommerce#cadastrar'
  post '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  patch '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  get '/cliente/sair', to: 'ecommerce#sair'
  get '/cliente/compra-concluida', to: 'ecommerce#compra_concluida'
  post '/cliente/concluir-pagamento', to: 'ecommerce#concluir_pagamento'
  get '/cliente/pagamento', to: 'ecommerce#confirmar_pagamento'

  
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  has_many :pedido_produtos
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:cliente_id, :valor_total)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @pedido.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h4>

      <ul>
      <% @pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cliente, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :cliente_id, Cliente.all.collect{|c| [c.nome, c.id]}, {}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor_total, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor_total, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Votar
  <% end %>
  <%= link_to @pedido, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostar
  <% end %>
  <h1>Editando pedido</h1>
</div>

<%= render 'form' %>

app/views/pedidos/index.html.erb
<div class="page-header">
  <%= link_to new_pedido_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Pedido
  <% end %>
  <h1>Listando pedidos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Cliente</th>
            <th>Valor total</th>
            <th>Itens</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @pedidos) do |pedido| %>
          <td><%= pedido.cliente.nome %></td>
          <td><%= pedido.valor_total %></td>
          <td><%= link_to 'Itens', pedido_pedido_produtos_path(pedido) %></td>
          <td><%= link_to 'Mostar', pedido %></td>
          <td><%= link_to 'Editar', edit_pedido_path(pedido) %></td>
          <td><%= link_to 'Deletar', pedido, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pedidos/new.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo pedido</h1>
</div>

<%= render 'form' %>

app/views/pedidos/show.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_pedido_path(@pedido), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar pedido</h1>
</div>

<dl class="dl-horizontal">
  <dt>Cliente:</dt>
  <dd><%= @pedido.cliente.nome %></dd>

  <dt>Valor total:</dt>
  <dd><%= @pedido.valor_total %></dd>
<dd>
  <ul>
    <% @pedido.pedido_produtos.each do |pp| %>
    <li>
      <%= pp.produto.nome %> - Valor Unidade R$ <%= pp.valor %>
    </li>
    <% end %>
  </ul>
</dd>
</dl>