config/routes.rb
Rails.application.routes.draw do
  resources :administradores
  resources :pedidos do
    resources :pedido_produtos
  end
  resources :clientes
  resources :produtos 
  resources :tipo_produtos

  #admin
  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/sair', to: 'login#sair'

  #autenticacao
  get '/login', to: 'login#index'
  post '/login/autenticar', to: 'login#autenticar'
  get '/login/sair', to: 'login#sair'
  
  # ecommerce
  get '/produto/:produto_id', to: 'ecommerce#index'
  get '/produto/:produto_id/adicionar', to: 'ecommerce#adicionar'
  get '/produto/:produto_id/remover', to: 'ecommerce#remover'
  get '/carrinho', to: 'ecommerce#carrinho'
  get '/carrinho/fechar', to: 'ecommerce#fechar_carrinho'
  get '/cliente/logar', to: 'ecommerce#login'
  post '/cliente/login', to: 'ecommerce#fazer_login_cliente'
  get '/cliente/cadastrar', to: 'ecommerce#cadastrar'
  post '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  patch '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  get '/cliente/sair', to: 'ecommerce#sair'
  get '/cliente/compra-concluida', to: 'ecommerce#compra_concluida'
  post '/cliente/concluir-pagamento', to: 'ecommerce#concluir_pagamento'
  get '/cliente/pagamento', to: 'ecommerce#confirmar_pagamento'

  
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administradore.rb
class Administradore < ApplicationRecord
end

app/controllers/administradores_controller.rb
class AdministradoresController < ApplicationController
  before_action :set_administradore, only: %i[ show edit update destroy ]

  # GET /administradores or /administradores.json
  def index
    @administradores = Administradore.all
  end

  # GET /administradores/1 or /administradores/1.json
  def show
  end

  # GET /administradores/new
  def new
    @administradore = Administradore.new
  end

  # GET /administradores/1/edit
  def edit
  end

  # POST /administradores or /administradores.json
  def create
    @administradore = Administradore.new(administradore_params)

    respond_to do |format|
      if @administradore.save
        format.html { redirect_to @administradore, notice: "Administradore was successfully created." }
        format.json { render :show, status: :created, location: @administradore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administradore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradores/1 or /administradores/1.json
  def update
    respond_to do |format|
      if @administradore.update(administradore_params)
        format.html { redirect_to @administradore, notice: "Administradore was successfully updated." }
        format.json { render :show, status: :ok, location: @administradore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administradore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradores/1 or /administradores/1.json
  def destroy
    @administradore.destroy
    respond_to do |format|
      format.html { redirect_to administradores_url, notice: "Administradore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administradore
      @administradore = Administradore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administradore_params
      params.require(:administradore).permit(:nome, :email, :senha)
    end
end

app/helpers/administradores_helper.rb
module AdministradoresHelper

end

app/views/administradores/_form.html.erb
<%= form_for(@administradore, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @administradore.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@administradore.errors.count, "error") %> prohibited this administradore from being saved:</h4>

      <ul>
      <% @administradore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :senha, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :senha, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/administradores/edit.html.erb
<div class="page-header">
  <%= link_to administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Votar
  <% end %>
  <%= link_to @administradore, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostar
  <% end %>
  <h1>Editando administradore</h1>
</div>

<%= render 'form' %>

app/views/administradores/index.html.erb
<div class="page-header">
  <%= link_to new_administradore_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Administradore
  <% end %>
  <h1>Listando administradores</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Senha</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @administradores) do |administradore| %>
            <td><%= administradore.nome %></td>
            <td><%= administradore.email %></td>
            <td><%= administradore.senha %></td>
            <td><%= link_to 'Show', administradore %></td>
        <td><%= link_to 'Edit', edit_administradore_path(administradore) %></td>
        <td><%= link_to 'Destroy', administradore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/administradores/new.html.erb
<div class="page-header">
  <%= link_to administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo administradore</h1>
</div>

<%= render 'form' %>

app/views/administradores/show.html.erb
<div class="page-header">
  <%= link_to administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_administradore_path(@administradore), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar administradore</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @administradore.nome %></dd>

  <dt>Email:</dt>
  <dd><%= @administradore.email %></dd>

  <dt>Senha:</dt>
  <dd><%= @administradore.senha %></dd>

</dl>