config/routes.rb
Rails.application.routes.draw do
  resources :administradores
  resources :pedidos do
    resources :pedido_produtos
  end
  resources :clientes
  resources :produtos 
  resources :tipo_produtos

  #admin
  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/sair', to: 'login#sair'

  #autenticacao
  get '/login', to: 'login#index'
  post '/login/autenticar', to: 'login#autenticar'
  get '/login/sair', to: 'login#sair'
  
  # ecommerce
  get '/produto/:produto_id', to: 'ecommerce#index'
  get '/produto/:produto_id/adicionar', to: 'ecommerce#adicionar'
  get '/produto/:produto_id/remover', to: 'ecommerce#remover'
  get '/carrinho', to: 'ecommerce#carrinho'
  get '/carrinho/fechar', to: 'ecommerce#fechar_carrinho'
  get '/cliente/logar', to: 'ecommerce#login'
  post '/cliente/login', to: 'ecommerce#fazer_login_cliente'
  get '/cliente/cadastrar', to: 'ecommerce#cadastrar'
  post '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  patch '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  get '/cliente/sair', to: 'ecommerce#sair'
  get '/cliente/compra-concluida', to: 'ecommerce#compra_concluida'
  post '/cliente/concluir-pagamento', to: 'ecommerce#concluir_pagamento'
  get '/cliente/pagamento', to: 'ecommerce#confirmar_pagamento'

  
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tipo_produto.rb
class TipoProduto < ApplicationRecord
    has_many :produtos
end

app/controllers/tipo_produtos_controller.rb
class TipoProdutosController < ApplicationController
  before_action :set_tipo_produto, only: %i[ show edit update destroy ]

  # GET /tipo_produtos or /tipo_produtos.json
  def index
    @tipo_produtos = TipoProduto.all
  end

  # GET /tipo_produtos/1 or /tipo_produtos/1.json
  def show
  end

  # GET /tipo_produtos/new
  def new
    @tipo_produto = TipoProduto.new
  end

  # GET /tipo_produtos/1/edit
  def edit
  end

  # POST /tipo_produtos or /tipo_produtos.json
  def create
    @tipo_produto = TipoProduto.new(tipo_produto_params)

    respond_to do |format|
      if @tipo_produto.save
        format.html { redirect_to @tipo_produto, notice: "Tipo produto was successfully created." }
        format.json { render :show, status: :created, location: @tipo_produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_produtos/1 or /tipo_produtos/1.json
  def update
    respond_to do |format|
      if @tipo_produto.update(tipo_produto_params)
        format.html { redirect_to @tipo_produto, notice: "Tipo produto was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo_produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_produtos/1 or /tipo_produtos/1.json
  def destroy
    @tipo_produto.destroy
    respond_to do |format|
      format.html { redirect_to tipo_produtos_url, notice: "Tipo produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_produto
      @tipo_produto = TipoProduto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_produto_params
      params.require(:tipo_produto).permit(:nome)
    end
end

app/helpers/tipo_produtos_helper.rb
module TipoProdutosHelper
end

app/views/tipo_produtos/_form.html.erb
<%= form_for(@tipo_produto, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @tipo_produto.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@tipo_produto.errors.count, "error") %> prohibited this tipo_produto from being saved:</h4>

      <ul>
      <% @tipo_produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tipo_produtos/edit.html.erb
<div class="page-header">
  <%= link_to tipo_produto_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @tipo_produto, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Exibir
  <% end %>
  <h1>Editando Tipo Produto</h1>
</div>

<%= render 'form' %>

app/views/tipo_produtos/index.html.erb
<div class="page-header">
  <%= link_to new_tipo_produto_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus "></span>
    Novo Produto
  <% end %>
  <h1>Listando tipos de produtos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th colspan="3" class="text-center">Ações</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tipo_produtos) do |tipo_produto| %>
            <td><%= tipo_produto.nome %></td>
            <td><%= link_to 'Exibir', tipo_produto %></td>
        <td><%= link_to 'Editar', edit_tipo_produto_path(tipo_produto) %></td>
        <td><%= link_to 'Deletar', tipo_produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tipo_produtos/new.html.erb
<div class="page-header">
  <%= link_to tipo_produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Novo Tipo de Produto</h1>
</div>

<%= render 'form' %>

app/views/tipo_produtos/show.html.erb
<div class="page-header">
  <%= link_to tipo_produto_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_produto_path(@tipo_produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Exibir Tipo de Produto</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @tipo_produto.nome %></dd>
</dl>